# Generated by Django 3.1 on 2023-03-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='post_videos')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_photo')),
                ('see', models.PositiveIntegerField()),
                ('tag', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='article.category')),
            ],
        ),
    ]
